# Generated by Django 3.0.11 on 2020-12-22 19:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django_google_maps.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', django_google_maps.fields.AddressField(max_length=100)),
                ('cuisines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('notes', models.TextField(blank=True, max_length=5000, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('website', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
