# Generated by Django 3.0.11 on 2020-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresbud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
