# Generated by Django 3.0.11 on 2020-11-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myresbud', '0002_auto_20201128_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturant',
            name='posted_by',
        ),
    ]
